name: Build greenServe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build greenServe
        run: make clean all

      - name: Build libserver module
        run: make module MODULE=libserver.c

      - name: Upload greenServe binary
        uses: actions/upload-artifact@v4
        with:
          name: greenServe-linux-x86_64
          path: greenServe

      - name: Upload libserver module
        uses: actions/upload-artifact@v4
        with:
          name: greenServe-libserver-linux-x86_64
          path: build/modules/libserver.so
